const styles = {
  root: {
    backgroundColor: "white",
    margin: "0",
    marginBottom: "-10px",
    border: "1px solid black",
    borderRadius: "5px",
    position: "relative",
    padding: ".5rem",
    overflow: "hidden",
    cursor: "pointer",
    "&:hover svg": {
      opacity: 1,
    },
  },
  colors: {
    backgroundColor: "#daed184",
    height: "100px",
    width: "100%",
    borderRadius: "5px",
    overflow: "hidden",
  },
  title: {
    display: "flex",
    justifyContent: "space-between",
    margin: "0",
    color: "black",
    paddingTop: "0.5rem",
    position: "relative",
    fontSize: "1rem",
  },
  emoji: {
    marginLeft: "0.5rem",
    fontSize: "1.5rem",
  },
  miniColor: {
    height: "25%",
    width: "20%",
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
    marginBottom: "-4px",
  },
  delete: {
    position: "absolute",
    top: "0",
    right: "0",
    width: "20%",
    height: "20%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },
  deleteIcon: {
    color: "white",
    backgroundColor: "red",
    width: "100%",
    height: "100%",
    maxHeight: "30px",
    maxWidth: "30px",

    opacity: 0,
    transition: ".5s opacity ease",
  },
};
export default styles;
